FROM ubuntu:18.04

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

ENV REACT_APP_BACKEND_URL=http://localhost:8080/

RUN apt update && apt install -y curl && \
    curl -sL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt install -y nodejs && \
    npm install && \
    npm run build && \
    npm install -g serve && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get purge -y --auto-remove curl && \
    useradd -m appuser && \
    chown appuser /usr/src/app

CMD ["serve", "-s", "-l", "5000", "build"]
