FROM node:16-alpine3.14 AS build-env

EXPOSE 5000

WORKDIR /app

COPY . .

ENV REACT_APP_BACKEND_URL=http://localhost:8080/

RUN npm install && \
    npm run build && \
    npm install -g serve && \
    adduser -D appuser && \
    chown appuser /app

USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]


FROM nginx:1.19-alpine

COPY --from=build-env /app/build /usr/share/nginx/html
