version: '3'

services:

  redis:
    image: redis
    volumes:
      - ./redis-db:/data
  
  postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: db_postgres
    volumes:
      - ./psql-db:/var/lib/postgresql/dat

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  backend:
    image: backend
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: example
      REQUEST_ORIGIN: http://localhost:5000
    depends_on:
      - postgres

  frontend:
    image: frontend
    ports:
      - 5000:5000
