version: '3'

services: 
  ml-training: 
    image: ml-training
    build: ./ml-kurkkumopo-training-master
    volumes: 
      - model:/src/model 
      - imgs:/src/imgs 
       
  backend:
    image: ml-back
    build: ./ml-kurkkumopo-backend-master
    ports:
      - 5000:5000
    volumes:
      - model:/src/model

  frontend:
    image: ml-front
    build: ./ml-kurkkumopo-frontend-master
    ports:
      - 3000:3000

volumes: 
  model: 
  imgs:
