version: '3'

services:

  postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: db_postgres

  backend:
    build:
      context: ../../../material-applications/example-backend/
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: example
      REQUEST_ORIGIN: http://localhost:5000
    depends_on:
      - postgres

  frontend:
    build:
      context: ../../../material-applications/example-frontend/
    ports:
      - 5000:5000
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080
