version: '3'

services:

  redis:
      image: redis

  backend:
      build:
        context: ../../../material-applications/example-backend/
      ports:
        - 8080:8080
      environment:
        REDIS_HOST: redis
        REQUEST_ORIGIN: http://localhost:5000

  frontend:
      build:
        context: ../../../material-applications/example-frontend/
      ports:
        - 5000:5000
      environment:
        REACT_APP_BACKEND_URL: http://localhost:8080
